PREFIX ?= /usr/local
# packaging/build-deb.sh sets this per-distro to keep each container's build
# isolated; `?=` picks it up from the environment automatically when set.
CARGO_TARGET_DIR ?= target

.PHONY: build release debug man completions install uninstall clean test

build: release

release:
	cargo build --release

debug:
	cargo build

# gzip -n: no embedded filename/timestamp, so the compressed man page is
# byte-identical across rebuilds (matches Debian's reproducible-builds and
# lintian's manpage-not-compressed-with-max-compression expectations).
man:
	mkdir -p target/man
	gzip -9 -n -c packaging/coffer.1 > target/man/coffer.1.gz

# Generated by asking the already-built binary itself (clap_complete) -
# must run after the binary exists, so `install` below only calls this once
# it has ensured that (built it, or verified it's already there as root).
completions:
	mkdir -p target/completions
	$(CARGO_TARGET_DIR)/release/coffer completions bash > target/completions/coffer.bash
	$(CARGO_TARGET_DIR)/release/coffer completions zsh > target/completions/_coffer
	$(CARGO_TARGET_DIR)/release/coffer completions fish > target/completions/coffer.fish

# Building as root (typically via `sudo make install` run directly, without
# ./setup.sh) doesn't work reliably: root has no Rust toolchain of its own,
# and some setups don't even let root read into a locked-down $HOME - so
# skip the auto-build in that case and fail with a clear next step instead
# of letting cargo's confusing "could not find Cargo.toml" surface.
install: man
	@if [ "$$(id -u)" -eq 0 ]; then \
		if [ ! -r target/release/coffer ]; then \
			echo "error: target/release/coffer is missing or unreadable as root." >&2; \
			echo "Build it as your normal user first, then install:" >&2; \
			echo "    make release" >&2; \
			echo "    sudo make install" >&2; \
			echo "Or just run ./setup.sh, which handles this for you." >&2; \
			exit 1; \
		fi; \
	else \
		$(MAKE) release; \
	fi
	$(MAKE) completions
	install -Dm755 target/release/coffer $(DESTDIR)$(PREFIX)/bin/coffer
	install -Dm644 target/man/coffer.1.gz $(DESTDIR)$(PREFIX)/share/man/man1/coffer.1.gz
	install -Dm644 target/completions/coffer.bash $(DESTDIR)$(PREFIX)/share/bash-completion/completions/coffer
	install -Dm644 target/completions/_coffer $(DESTDIR)$(PREFIX)/share/zsh/site-functions/_coffer
	install -Dm644 target/completions/coffer.fish $(DESTDIR)$(PREFIX)/share/fish/vendor_completions.d/coffer.fish

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/coffer
	rm -f $(DESTDIR)$(PREFIX)/share/man/man1/coffer.1.gz
	rm -f $(DESTDIR)$(PREFIX)/share/bash-completion/completions/coffer
	rm -f $(DESTDIR)$(PREFIX)/share/zsh/site-functions/_coffer
	rm -f $(DESTDIR)$(PREFIX)/share/fish/vendor_completions.d/coffer.fish

test:
	cargo test

clean:
	cargo clean
