PREFIX ?= /usr/local
# packaging/build-deb.sh and build-rpm.sh set this per-distro to keep each
# container's build isolated; `?=` picks it up from the environment
# automatically when set.
CARGO_TARGET_DIR ?= target

.PHONY: build release debug man completions install uninstall clean test check-deps

# Also generates the man page and completions, so that the documented
# `make build` + `sudo make install` flow has everything ready before root
# gets involved (see `install` below for why root can't generate them).
build: release man completions

# Fail fast with a readable hint when the FUSE dev files or the Rust
# toolchain aren't installed yet - the usual case when `make` is run on a
# fresh machine before ./setup.sh. Without this, the first thing a user
# sees is fuser's build-script panic ("Package fuse3 was not found in the
# pkg-config search path"), several screens deep into cargo output.
check-deps:
	@command -v cargo >/dev/null 2>&1 || { \
		echo "error: cargo not found." >&2; \
		echo "Run ./setup.sh (installs a Rust toolchain via rustup), or if it is already installed:" >&2; \
		echo "    source \$$HOME/.cargo/env" >&2; \
		exit 1; }
	@command -v pkg-config >/dev/null 2>&1 && pkg-config --exists 'fuse3 >= 3.0.0' || { \
		echo "error: libfuse3 development files not found (pkg-config cannot resolve 'fuse3')." >&2; \
		echo "Run ./setup.sh (Debian/Ubuntu), or install them manually:" >&2; \
		echo "    sudo apt-get install pkg-config libfuse3-dev fuse3" >&2; \
		exit 1; }

release: check-deps
	cargo build --release

debug: check-deps
	cargo build

# gzip -n: no embedded filename/timestamp, so the compressed man page is
# byte-identical across rebuilds (matches Debian's reproducible-builds and
# lintian's manpage-not-compressed-with-max-compression expectations).
man:
	mkdir -p target/man
	gzip -9 -n -c packaging/coffer.1 > target/man/coffer.1.gz

# Generated by asking the already-built binary itself (clap_complete) -
# must run after the binary exists, so `install` below only calls this once
# it has ensured that (built it, or verified it's already there as root).
completions:
	mkdir -p target/completions
	$(CARGO_TARGET_DIR)/release/coffer completions bash > target/completions/coffer.bash
	$(CARGO_TARGET_DIR)/release/coffer completions zsh > target/completions/_coffer
	$(CARGO_TARGET_DIR)/release/coffer completions fish > target/completions/coffer.fish

# Building - or even just generating the man page and completions - as root
# (typically via `sudo make install` run directly, without ./setup.sh)
# doesn't work reliably: root has no Rust toolchain of its own, some setups
# don't let root read into a locked-down $HOME, and on an NFS home with
# root_squash root can't write into target/ at all (gzip fails with
# "Permission denied" on the man page). So as root nothing is built or
# generated here: everything is expected to exist already from a `make
# build` run as the normal user, and a missing piece fails with a clear
# next step instead of letting cargo's confusing "could not find
# Cargo.toml" (or that gzip error) surface.
install:
	@if [ "$$(id -u)" -eq 0 ]; then \
		for f in target/release/coffer target/man/coffer.1.gz \
		         target/completions/coffer.bash target/completions/_coffer target/completions/coffer.fish; do \
			[ -r "$$f" ] && continue; \
			echo "error: $$f is missing or unreadable as root." >&2; \
			echo "Build everything as your normal user first, then install:" >&2; \
			echo "    make build" >&2; \
			echo "    sudo make install" >&2; \
			echo "Or just run ./setup.sh, which handles this for you." >&2; \
			exit 1; \
		done; \
	else \
		$(MAKE) build; \
	fi
	install -Dm755 target/release/coffer $(DESTDIR)$(PREFIX)/bin/coffer
	install -Dm644 target/man/coffer.1.gz $(DESTDIR)$(PREFIX)/share/man/man1/coffer.1.gz
	install -Dm644 target/completions/coffer.bash $(DESTDIR)$(PREFIX)/share/bash-completion/completions/coffer
	install -Dm644 target/completions/_coffer $(DESTDIR)$(PREFIX)/share/zsh/site-functions/_coffer
	install -Dm644 target/completions/coffer.fish $(DESTDIR)$(PREFIX)/share/fish/vendor_completions.d/coffer.fish

uninstall:
	rm -f $(DESTDIR)$(PREFIX)/bin/coffer
	rm -f $(DESTDIR)$(PREFIX)/share/man/man1/coffer.1.gz
	rm -f $(DESTDIR)$(PREFIX)/share/bash-completion/completions/coffer
	rm -f $(DESTDIR)$(PREFIX)/share/zsh/site-functions/_coffer
	rm -f $(DESTDIR)$(PREFIX)/share/fish/vendor_completions.d/coffer.fish

test: check-deps
	cargo test

clean:
	cargo clean
